"""third migration

Revision ID: a2cf56783991
Revises: a49992a3d8cd
Create Date: 2020-05-14 18:49:36.261681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cf56783991'
down_revision = 'a49992a3d8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('tickets_bought', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['accounts.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
